### ISSUE TITLE
Compatibility with multiverse-inventories.

### ISSUE THREAD

**Issue by gortador** [Azlagor322/LiteBase#2]
It would be interesting to be able to make this plugin compatible with the multiverse-inventories plugin, so that players' inventories can leave with them when they visit litebase, currently the inventories are separate, and I haven't found a way to share them , even putting worlds on "Whitelist" does not work.
As multiverse-inventories is widely used I think that this will improve the number of administrators interested in this very interesting plugin
;-)

**Comment by Azlagor322** [comment]
Hello. Thanks for your feedback <3
You can discuss this in our Discord channel. I have already received this request and am actively adding support for multiverse inventories

**Comment by Azlagor322** [comment]
![image](https://github.com/Azlagor322/LiteBase/assets/136051831/fee6b08b-dec8-4727-910c-ac52b3cf4655)
use 2.2.7+ version
